### ISSUE TITLE
vlingo-auth-authservice example does not start

### ISSUE THREAD

**Issue by jakzal** [vlingo/vlingo-examples#110]
`java -jar target/vlingo-auth-authservice-1.6.0-jar-with-dependencies.jar`

```
====================
authservice: started
====================
vlingo/http: Generating handler dispatcher for main: io.vlingo.auth.infra.resource.PermissionResource
vlingo/http: Generating handler dispatcher for test: io.vlingo.auth.infra.resource.PermissionResource
java.lang.IllegalArgumentException: ConfigurationResource instance with dispatcher for io.vlingo.auth.infra.resource.PermissionResource not created because: Cannot generate resource dispatcher class for io.vlingo.auth.infra.resource.PermissionResource because there is no corresponding:
target/test-classes/io/vlingo/auth/infra/resource/PermissionResource.class
        at io.vlingo.http.resource.ConfigurationResource.tryGenerateCompile(ConfigurationResource.java:136)
        at io.vlingo.http.resource.ConfigurationResource.tryGenerateCompile(ConfigurationResource.java:118)
        at io.vlingo.http.resource.ConfigurationResource.newResourceFor(ConfigurationResource.java:58)
        at io.vlingo.http.resource.Loader.resourceFor(Loader.java:353)
        at io.vlingo.http.resource.Loader.loadResource(Loader.java:155)
        at io.vlingo.http.resource.Loader.loadResources(Loader.java:73)
        at io.vlingo.http.resource.Server.startWith(Server.java:46)
        at io.vlingo.http.resource.Server.startWith(Server.java:33)
        at io.vlingo.authservice.infra.Bootstrap.<init>(Bootstrap.java:21)
        at io.vlingo.authservice.infra.Bootstrap.instance(Bootstrap.java:56)
        at io.vlingo.authservice.infra.Bootstrap.main(Bootstrap.java:66)
Caused by: java.lang.IllegalArgumentException: Cannot generate resource dispatcher class for io.vlingo.auth.infra.resource.PermissionResource because there is no corresponding:
target/test-classes/io/vlingo/auth/infra/resource/PermissionResource.class
        at io.vlingo.http.resource.ResourceDispatcherGenerator.generateFor(ResourceDispatcherGenerator.java:89)
        at io.vlingo.http.resource.ConfigurationResource.tryGenerateCompile(ConfigurationResource.java:131)
        ... 10 more
vlingo/http: Failed to load resource: permission because: ConfigurationResource cannot be created for: io.vlingo.auth.infra.resource.PermissionResource
Exception in thread "main" java.lang.IllegalStateException: ConfigurationResource cannot be created for: io.vlingo.auth.infra.resource.PermissionResource
        at io.vlingo.http.resource.Loader.resourceFor(Loader.java:356)
        at io.vlingo.http.resource.Loader.loadResource(Loader.java:155)
        at io.vlingo.http.resource.Loader.loadResources(Loader.java:73)
        at io.vlingo.http.resource.Server.startWith(Server.java:46)
        at io.vlingo.http.resource.Server.startWith(Server.java:33)
        at io.vlingo.authservice.infra.Bootstrap.<init>(Bootstrap.java:21)
        at io.vlingo.authservice.infra.Bootstrap.instance(Bootstrap.java:56)
        at io.vlingo.authservice.infra.Bootstrap.main(Bootstrap.java:66)
```

**Comment by VaughnVernon** [comment]
I don't know why these would fail now. This particular example has been building and testing correctly for more than two years. I am not attached to this example, but I am concerned that there may be an underlying cause that should be addressed before removing it from the repository.

**Comment by jakzal** [comment]
Actualy, this example doesn't have any tests. It fails when you try run the jar and it seems that it's actually a problem in xoom-auth.

**Comment by VaughnVernon** [comment]
I think I now remember. This was a service to provide mock data for the auth UI developer a few years ago.

It should be deleted. I see no long-term usefulness. It's not even a decent example of using auth.

**Comment by jakzal** [comment]
Removed 👍
