### ISSUE TITLE
http-backend fails with out of memory WHEN client hangup.

### ISSUE THREAD

**Issue by anderskristian** [vlingo/vlingo-examples#59]
When I run the http-backend / http-frontend application - I get out of memory

The problem can be reproduced by starting http-backend and running below code

* try to start a SSE stream
* Let http client make a hangup.
* The problem comes in code **Header.copy()**
* I cannot understand what is going on - I am still working on understanding http-backend 
* below ```curl``` make hangup after 10 seconds.
* I have tried to put try/catch around the header copy and just ignore the error - but it will not stop the error. It seems to be something in other part of the code that I do not fully master.
* I am working on branch ```origin/feature/doc-http-server-vault``` - where I try to understand http-server - it is work in progress.

```

curl --request GET  \
       --header "X-Correlation-ID:PrivateTokenSynchronizerActor-tokens" \
       --header "Accept:text/event-stream" --max-time 10 \
       http://localhost:8082/vaultstreams/tokens

```

This is a log (the exception is repeated many times)

```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at io.vlingo.http.Header$Headers.copy(Header.java:122)
	at io.vlingo.http.resource.sse.SseClient.sendInitialResponse(SseClient.java:82)
	at io.vlingo.http.resource.sse.SseClient.<init>(SseClient.java:48)
	at io.vlingo.http.resource.sse.SseClient.<init>(SseClient.java:52)
	at io.vlingo.http.resource.sse.SseStreamResource.unsubscribeFromStream(SseStreamResource.java:67)
	at io.vlingo.http.resource.sse.SseStreamResourceDispatcher.lambda$dispatchToHandlerWith$1(SseStreamResourceDispatcher.java:42)
	at io.vlingo.http.resource.ResourceRequestHandlerActor.handleFor(ResourceRequestHandlerActor.java:31)
	at io.vlingo.http.resource.ResourceRequestHandler__Proxy.lambda$handleFor$f94799c1$1(ResourceRequestHandler__Proxy.java:35)
	at io.vlingo.actors.LocalMessage.internalDeliver(LocalMessage.java:121)
	at io.vlingo.actors.LocalMessage.deliver(LocalMessage.java:53)
	at io.vlingo.actors.plugin.mailbox.concurrentqueue.ConcurrentQueueMailbox.run(ConcurrentQueueMailbox.java:100)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

Last goodby to the JVM is - talks about **UncaughtExceptionHandler**

```
java.util.ConcurrentModificationException
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-2-thread-17"

java.util.ConcurrentModificationException
copy headerConnection: keep-alive
copy headerContent-Type: text/event-stream;charset=utf-8
copy headerCache-Control: no-cache
java.util.ConcurrentModificationException
copy headerX-Correlation-ID: PrivateTokenSynchronizerActor-tokens
java.util.ConcurrentModificationException
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
Disconnected from the target VM, address: '127.0.0.1:55235', transport: 'socket'
Exception in thread "pool-2-thread-16" Exception in thread "pool-2-thread-8" Exception in thread "pool-2-thread-4" Exception in thread "pool-2-thread-9" *** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message can't create byte arrau at JPLISAgent.c line: 813

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-2-thread-16"

```

**Comment by anderskristian** [comment]
@VaughnVernon 
The system does not fail any longer when hangup 
from v.1.2.6
